### ISSUE TITLE
Load Failed

### ISSUE THREAD

**Issue by adreaver** [jngo102/DamageValues#1]
Game Version 1.5.78.114833 (Game Pass)
Modding API Version 1.5.78.11833-71 (Scarab)
Mod Version 1.0.0.0
Downloaded 7/9/2022

Initially failed to load with several other mods. Still failed with all other mods disabled.

ModLog.txt:
[INFO]:[API] - Starting mod loading
[INFO]:[API] - Loading Global Settings
[INFO]:[API] - Deleting modlogs older than 7 days ago
[INFO]:[DamageValues] - Initializing
[INFO]:[DamageValues] - Loading Global Settings
[INFO]:[API] - Creating mod preloads
[ERROR]:[API] - Failed to load Mod `Damage Values`
[ERROR]:[API] - System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\WindowsApps\TeamCherry.15373CD61C66B_5.80.11835.0_x64__y4jvztpgccj42\Hollow Knight_Data\Managed\Mods\DamageValues'.
[ERROR]:[API] -   at System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) [0x000f7] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) [0x00006] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () [0x00054] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) [0x000d6] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0x00009] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.Directory.EnumerateFileSystemNames (System.String path, System.String searchPattern, System.IO.SearchOption searchOption, System.Boolean includeFiles, System.Boolean includeDirs) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.Directory.InternalEnumerateFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at System.IO.Directory.EnumerateFiles (System.String path) [0x0000e] in <9577ac7a62ef43179789031239ba8798>:0 
[ERROR]:[API] -   at DamageValues.DamageValues.Initialize () [0x00000] in /home/runner/work/DamageValues/DamageValues/DamageValues.cs:24 
[ERROR]:[API] -   at Modding.Mod.Initialize (System.Collections.Generic.Dictionary`2[TKey,TValue] preloadedObjects) [0x00000] in <2b54cdaf7a934f0eb297d50c4090ea9f>:0 
[ERROR]:[API] -   at Modding.ModLoader.LoadMod (Modding.ModLoader+ModInstance mod, System.Boolean updateModText, System.Collections.Generic.Dictionary`2[TKey,TValue] preloadedObjects) [0x00022] in <2b54cdaf7a934f0eb297d50c4090ea9f>:0 
[INFO]:[API] - Finished loading mods:
[INFO]:[API] - Modding API: 1.5.78.11833-71
[INFO]:[API] - Damage Values : Failed to initialize! Check ModLog.txt
[INFO]:[API] - 
[INFO]:[API] - Preloaded reflection in 2456ms

**Comment by jngo102** [comment]
Can you check your filesystem for whether the folder `C:\Program Files\WindowsApps\TeamCherry.15373CD61C66B_5.80.11835.0_x64__y4jvztpgccj42\Hollow Knight_Data\Managed\Mods\DamageValues` exists?

**Comment by adreaver** [comment]
Yes, I have it there. Includes DamageValues.dll, DamageValues.pdb, Default.png, ReadMe.md

**Comment by adreaver** [comment]
I fixed it - when the mod was installed by Scarab, it named the folder "Damage Values" instead of "DamageValues" (note the space). Removing the space, then relaunching the game fixed it.

**Comment by SFGrenade** [comment]
should be fixed once the version with https://github.com/jngo102/DamageValues/pull/4 is on scarab
