### ISSUE TITLE
bug when installing the mod

### ISSUE THREAD

**Issue by DamageMaximo** [jngo102/DamageValues#3]
When installing the mod it creates the folder "Damage Values" while it tries to locate "DamageValues" and because of that, it doesn't load, removing the space fixes it, but it would be nice if the problem didn't happen

**Comment by DamageMaximo** [comment]
Great mod, just needs a way to size down the number if the player wishes to

**Comment by SFGrenade** [comment]
should be fixed once the version with https://github.com/jngo102/DamageValues/pull/4 is on scarab
